(* generated by dune *)

(** @canonical Callgraph.Callgraph_api *)
module Callgraph_api = Callgraph__Callgraph_api

(** @canonical Callgraph.Cg *)
module Cg = Callgraph__Cg

(** @canonical Callgraph.Options *)
module Options = Callgraph__Options

(** @canonical Callgraph.Register *)
module Register = Callgraph__Register

(** @canonical Callgraph.Requests *)
module Requests = Callgraph__Requests

(** @canonical Callgraph.Services *)
module Services = Callgraph__Services

(** @canonical Callgraph.Subgraph *)
module Subgraph = Callgraph__Subgraph

(** @canonical Callgraph.Uses *)
module Uses = Callgraph__Uses

module Callgraph__ = struct end
[@@deprecated "this module is shadowed"]
