(* generated by dune *)

(** @canonical RteGen.Api *)
module Api = RteGen__Api

(** @canonical RteGen.Flags *)
module Flags = RteGen__Flags

(** @canonical RteGen.Generator *)
module Generator = RteGen__Generator

(** @canonical RteGen.Options *)
module Options = RteGen__Options

(** @canonical RteGen.Register *)
module Register = RteGen__Register

(** @canonical RteGen.Rte *)
module Rte = RteGen__Rte

(** @canonical RteGen.Visit *)
module Visit = RteGen__Visit

module RteGen__ = struct end
[@@deprecated "this module is shadowed"]
