(* generated by dune *)

(** @canonical Constant_Propagation.Api *)
module Api = Constant_Propagation__Api

(** @canonical Constant_Propagation.PropagationParameters *)
module PropagationParameters = Constant_Propagation__PropagationParameters

module Constant_Propagation__ = struct end
[@@deprecated "this module is shadowed"]
