(* generated by dune *)

(** @canonical Sparecode.Globs *)
module Globs = Sparecode__Globs

(** @canonical Sparecode.Register *)
module Register = Sparecode__Register

(** @canonical Sparecode.Spare_marks *)
module Spare_marks = Sparecode__Spare_marks

(** @canonical Sparecode.Sparecode_params *)
module Sparecode_params = Sparecode__Sparecode_params

(** @canonical Sparecode.Transform *)
module Transform = Sparecode__Transform

module Sparecode__ = struct end
[@@deprecated "this module is shadowed"]
