(* generated by dune *)

(** @canonical Markdown_report.Mardown_report *)
module Mardown_report = Markdown_report__Mardown_report

(** @canonical Markdown_report.Md_gen *)
module Md_gen = Markdown_report__Md_gen

(** @canonical Markdown_report.Mdr_params *)
module Mdr_params = Markdown_report__Mdr_params

(** @canonical Markdown_report.Mdr_register *)
module Mdr_register = Markdown_report__Mdr_register

(** @canonical Markdown_report.Parse_remarks *)
module Parse_remarks = Markdown_report__Parse_remarks

(** @canonical Markdown_report.Sarif *)
module Sarif = Markdown_report__Sarif

(** @canonical Markdown_report.Sarif_gen *)
module Sarif_gen = Markdown_report__Sarif_gen
