name: "Nix"
on:
  pull_request:
  push:
    branches:
      - 414-LTS
jobs:
  # tests:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout tree
  #       uses: actions/checkout@v4
  #       with:
  #         submodules: true
  #     - name: nix
  #       uses: cachix/install-nix-action@v30
  #       with:
  #         nix_path: nixpkgs=channel:nixos-unstable
  #     - run: nix develop .#check -c make nix-tests
  fmt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout tree
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: nix
        uses: cachix/install-nix-action@v30
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - run: nix develop .#fmt -c make nix-fmt
