(* generated by dune *)

(** @canonical Metrics.Css_html *)
module Css_html = Metrics__Css_html

(** @canonical Metrics.Metrics_acsl *)
module Metrics_acsl = Metrics__Metrics_acsl

(** @canonical Metrics.Metrics_base *)
module Metrics_base = Metrics__Metrics_base

(** @canonical Metrics.Metrics_cabs *)
module Metrics_cabs = Metrics__Metrics_cabs

(** @canonical Metrics.Metrics_cilast *)
module Metrics_cilast = Metrics__Metrics_cilast

(** @canonical Metrics.Metrics_coverage *)
module Metrics_coverage = Metrics__Metrics_coverage

(** @canonical Metrics.Metrics_parameters *)
module Metrics_parameters = Metrics__Metrics_parameters

(** @canonical Metrics.Metrics_pivot *)
module Metrics_pivot = Metrics__Metrics_pivot

(** @canonical Metrics.Register *)
module Register = Metrics__Register

module Metrics__ = struct end
[@@deprecated "this module is shadowed"]
