(* generated by dune *)

(** @canonical Impact.Compute_impact *)
module Compute_impact = Impact__Compute_impact

(** @canonical Impact.Options *)
module Options = Impact__Options

(** @canonical Impact.Pdg_aux *)
module Pdg_aux = Impact__Pdg_aux

(** @canonical Impact.Reason_graph *)
module Reason_graph = Impact__Reason_graph

(** @canonical Impact.Register *)
module Register = Impact__Register
