(* generated by dune *)

(** @canonical Pdg_types.PdgIndex *)
module PdgIndex = Pdg_types__PdgIndex

(** @canonical Pdg_types.PdgMarks *)
module PdgMarks = Pdg_types__PdgMarks

(** @canonical Pdg_types.PdgTypes *)
module PdgTypes = Pdg_types__PdgTypes

module Pdg_types__ = struct end
[@@deprecated "this module is shadowed"]
