
OCAMLBEST   = opt
BIGINTLIB   = zarith
MPFRLIB     = 
INFERLIB    = 
STACKIFY    = yes
INCLUDE     = -I /home/bhaskar/.opam/default/lib/zarith -I "/home/bhaskar/.opam/default/lib/why3"
EXTPKGS     = menhirLib str unix num dynlink zip     

OCAMLFIND   = ocamlfind

BINDIR      = "/home/bhaskar/.opam/default/bin"
LIBDIR      = "/home/bhaskar/.opam/default/lib/why3"
DATADIR     = "/home/bhaskar/.opam/default/share/why3"

