(* generated by dune *)

(** @canonical Slicing.Api *)
module Api = Slicing__Api

(** @canonical Slicing.Fct_slice *)
module Fct_slice = Slicing__Fct_slice

(** @canonical Slicing.PrintSlice *)
module PrintSlice = Slicing__PrintSlice

(** @canonical Slicing.Register *)
module Register = Slicing__Register

(** @canonical Slicing.SlicingActions *)
module SlicingActions = Slicing__SlicingActions

(** @canonical Slicing.SlicingCmds *)
module SlicingCmds = Slicing__SlicingCmds

(** @canonical Slicing.SlicingInternals *)
module SlicingInternals = Slicing__SlicingInternals

(** @canonical Slicing.SlicingMacros *)
module SlicingMacros = Slicing__SlicingMacros

(** @canonical Slicing.SlicingMarks *)
module SlicingMarks = Slicing__SlicingMarks

(** @canonical Slicing.SlicingParameters *)
module SlicingParameters = Slicing__SlicingParameters

(** @canonical Slicing.SlicingProject *)
module SlicingProject = Slicing__SlicingProject

(** @canonical Slicing.SlicingSelect *)
module SlicingSelect = Slicing__SlicingSelect

(** @canonical Slicing.SlicingState *)
module SlicingState = Slicing__SlicingState

(** @canonical Slicing.SlicingTransform *)
module SlicingTransform = Slicing__SlicingTransform

(** @canonical Slicing.SlicingTypes *)
module SlicingTypes = Slicing__SlicingTypes
