(* generated by dune *)

(** @canonical Obfuscator.Dictionary *)
module Dictionary = Obfuscator__Dictionary

(** @canonical Obfuscator.Obfuscate *)
module Obfuscate = Obfuscator__Obfuscate

(** @canonical Obfuscator.Obfuscator_kind *)
module Obfuscator_kind = Obfuscator__Obfuscator_kind

(** @canonical Obfuscator.Obfuscator_register *)
module Obfuscator_register = Obfuscator__Obfuscator_register

(** @canonical Obfuscator.Options *)
module Options = Obfuscator__Options

module Obfuscator__ = struct end
[@@deprecated "this module is shadowed"]
