(* generated by dune *)

(** @canonical Metrics_gui.Metrics_gui_panels *)
module Metrics_gui_panels = Metrics_gui__Metrics_gui_panels

(** @canonical Metrics_gui.Register_gui *)
module Register_gui = Metrics_gui__Register_gui
