(* generated by dune *)

(** @canonical Instantiate.Basic_alloc *)
module Basic_alloc = Instantiate__Basic_alloc

(** @canonical Instantiate.Basic_blocks *)
module Basic_blocks = Instantiate__Basic_blocks

(** @canonical Instantiate.Calloc *)
module Calloc = Instantiate__Calloc

(** @canonical Instantiate.Free *)
module Free = Instantiate__Free

(** @canonical Instantiate.Global_context *)
module Global_context = Instantiate__Global_context

(** @canonical Instantiate.Instantiator_builder *)
module Instantiator_builder = Instantiate__Instantiator_builder

(** @canonical Instantiate.Malloc *)
module Malloc = Instantiate__Malloc

(** @canonical Instantiate.Mem_utils *)
module Mem_utils = Instantiate__Mem_utils

(** @canonical Instantiate.Memcmp *)
module Memcmp = Instantiate__Memcmp

(** @canonical Instantiate.Memcpy *)
module Memcpy = Instantiate__Memcpy

(** @canonical Instantiate.Memmove *)
module Memmove = Instantiate__Memmove

(** @canonical Instantiate.Memset *)
module Memset = Instantiate__Memset

(** @canonical Instantiate.Options *)
module Options = Instantiate__Options

(** @canonical Instantiate.Register *)
module Register = Instantiate__Register

(** @canonical Instantiate.Transform *)
module Transform = Instantiate__Transform

module Instantiate__ = struct end
[@@deprecated "this module is shadowed"]
