(* generated by dune *)

(** @canonical OcplibSimplex.AssertBounds *)
module AssertBounds = OcplibSimplex__AssertBounds

(** @canonical OcplibSimplex.Basic *)
module Basic = OcplibSimplex__Basic

(** @canonical OcplibSimplex.Core *)
module Core = OcplibSimplex__Core

(** @canonical OcplibSimplex.CoreSig *)
module CoreSig = OcplibSimplex__CoreSig

(** @canonical OcplibSimplex.ExtSigs *)
module ExtSigs = OcplibSimplex__ExtSigs

(** @canonical OcplibSimplex.Polys *)
module Polys = OcplibSimplex__Polys

(** @canonical OcplibSimplex.Rat2 *)
module Rat2 = OcplibSimplex__Rat2

(** @canonical OcplibSimplex.Result *)
module Result = OcplibSimplex__Result

(** @canonical OcplibSimplex.SolveBounds *)
module SolveBounds = OcplibSimplex__SolveBounds

(** @canonical OcplibSimplex.Version *)
module Version = OcplibSimplex__Version
