(* generated by dune *)

(** @canonical Scope.Datascope *)
module Datascope = Scope__Datascope

(** @canonical Scope.Defs *)
module Defs = Scope__Defs

(** @canonical Scope.Zones *)
module Zones = Scope__Zones

module Scope__ = struct end
[@@deprecated "this module is shadowed"]
