(* generated by dune *)

(** @canonical Pdg.Annot *)
module Annot = Pdg__Annot

(** @canonical Pdg.Api *)
module Api = Pdg__Api

(** @canonical Pdg.Build *)
module Build = Pdg__Build

(** @canonical Pdg.CtrlDpds *)
module CtrlDpds = Pdg__CtrlDpds

(** @canonical Pdg.Marks *)
module Marks = Pdg__Marks

(** @canonical Pdg.Pdg_parameters *)
module Pdg_parameters = Pdg__Pdg_parameters

(** @canonical Pdg.Pdg_state *)
module Pdg_state = Pdg__Pdg_state

(** @canonical Pdg.Pdg_tbl *)
module Pdg_tbl = Pdg__Pdg_tbl

(** @canonical Pdg.Register *)
module Register = Pdg__Register

(** @canonical Pdg.Sets *)
module Sets = Pdg__Sets

module Pdg__ = struct end
[@@deprecated "this module is shadowed"]
