(* generated by dune *)

(** @canonical Syntacticsearch.CodeQuery *)
module CodeQuery = Syntacticsearch__CodeQuery

(** @canonical Syntacticsearch.FuncDatatype *)
module FuncDatatype = Syntacticsearch__FuncDatatype

(** @canonical Syntacticsearch.FuncFunction *)
module FuncFunction = Syntacticsearch__FuncFunction

(** @canonical Syntacticsearch.FuncVar *)
module FuncVar = Syntacticsearch__FuncVar

(** @canonical Syntacticsearch.QueryMapping *)
module QueryMapping = Syntacticsearch__QueryMapping

(** @canonical Syntacticsearch.ResultPrinter *)
module ResultPrinter = Syntacticsearch__ResultPrinter
