(* generated by dune *)

(** @canonical Dive.Build *)
module Build = Dive__Build

(** @canonical Dive.Callstack *)
module Callstack = Dive__Callstack

(** @canonical Dive.Context *)
module Context = Dive__Context

(** @canonical Dive.Dive_graph *)
module Dive_graph = Dive__Dive_graph

(** @canonical Dive.Dive_types *)
module Dive_types = Dive__Dive_types

(** @canonical Dive.Main *)
module Main = Dive__Main

(** @canonical Dive.Node_kind *)
module Node_kind = Dive__Node_kind

(** @canonical Dive.Node_range *)
module Node_range = Dive__Node_range

(** @canonical Dive.Self *)
module Self = Dive__Self

(** @canonical Dive.Server_interface *)
module Server_interface = Dive__Server_interface

module Dive__ = struct end
[@@deprecated "this module is shadowed"]
