(* generated by dune *)

(** @canonical Aorai.Aorai_dataflow *)
module Aorai_dataflow = Aorai__Aorai_dataflow

(** @canonical Aorai.Aorai_eva_analysis *)
module Aorai_eva_analysis = Aorai__Aorai_eva_analysis

(** @canonical Aorai.Aorai_graph *)
module Aorai_graph = Aorai__Aorai_graph

(** @canonical Aorai.Aorai_metavariables *)
module Aorai_metavariables = Aorai__Aorai_metavariables

(** @canonical Aorai.Aorai_option *)
module Aorai_option = Aorai__Aorai_option

(** @canonical Aorai.Aorai_register *)
module Aorai_register = Aorai__Aorai_register

(** @canonical Aorai.Aorai_utils *)
module Aorai_utils = Aorai__Aorai_utils

(** @canonical Aorai.Aorai_visitors *)
module Aorai_visitors = Aorai__Aorai_visitors

(** @canonical Aorai.Automaton_ast *)
module Automaton_ast = Aorai__Automaton_ast

(** @canonical Aorai.Bool3 *)
module Bool3 = Aorai__Bool3

(** @canonical Aorai.Data_for_aorai *)
module Data_for_aorai = Aorai__Data_for_aorai

(** @canonical Aorai.Logic_simplification *)
module Logic_simplification = Aorai__Logic_simplification

(** @canonical Aorai.Path_analysis *)
module Path_analysis = Aorai__Path_analysis

(** @canonical Aorai.Pretty_automaton *)
module Pretty_automaton = Aorai__Pretty_automaton

(** @canonical Aorai.Utils_parser *)
module Utils_parser = Aorai__Utils_parser

(** @canonical Aorai.Yalexer *)
module Yalexer = Aorai__Yalexer

(** @canonical Aorai.Yaparser *)
module Yaparser = Aorai__Yaparser

module Aorai__ = struct end
[@@deprecated "this module is shadowed"]
