(* generated by dune *)

(** @canonical Variadic.Builder *)
module Builder = Variadic__Builder

(** @canonical Variadic.Classify *)
module Classify = Variadic__Classify

(** @canonical Variadic.Environment *)
module Environment = Variadic__Environment

(** @canonical Variadic.Extends *)
module Extends = Variadic__Extends

(** @canonical Variadic.Format_parser *)
module Format_parser = Variadic__Format_parser

(** @canonical Variadic.Format_pprint *)
module Format_pprint = Variadic__Format_pprint

(** @canonical Variadic.Format_string *)
module Format_string = Variadic__Format_string

(** @canonical Variadic.Format_typer *)
module Format_typer = Variadic__Format_typer

(** @canonical Variadic.Format_types *)
module Format_types = Variadic__Format_types

(** @canonical Variadic.Generic *)
module Generic = Variadic__Generic

(** @canonical Variadic.Options *)
module Options = Variadic__Options

(** @canonical Variadic.Register *)
module Register = Variadic__Register

(** @canonical Variadic.Replacements *)
module Replacements = Variadic__Replacements

(** @canonical Variadic.Standard *)
module Standard = Variadic__Standard

(** @canonical Variadic.Translate *)
module Translate = Variadic__Translate

(** @canonical Variadic.Va_types *)
module Va_types = Variadic__Va_types

module Variadic__ = struct end
[@@deprecated "this module is shadowed"]
