(* generated by dune *)

(** @canonical Occurrence.Options *)
module Options = Occurrence__Options

(** @canonical Occurrence.Register *)
module Register = Occurrence__Register

module Occurrence__ = struct end
[@@deprecated "this module is shadowed"]
