(* generated by dune *)

(** @canonical Eva_gui.Gui_callstacks_filters *)
module Gui_callstacks_filters = Eva_gui__Gui_callstacks_filters

(** @canonical Eva_gui.Gui_callstacks_manager *)
module Gui_callstacks_manager = Eva_gui__Gui_callstacks_manager

(** @canonical Eva_gui.Gui_eval *)
module Gui_eval = Eva_gui__Gui_eval

(** @canonical Eva_gui.Gui_red *)
module Gui_red = Eva_gui__Gui_red

(** @canonical Eva_gui.Gui_types *)
module Gui_types = Eva_gui__Gui_types

(** @canonical Eva_gui.Register_gui *)
module Register_gui = Eva_gui__Register_gui
