(* generated by dune *)

(** @canonical Frama_c_kernel.Abstract_interp *)
module Abstract_interp = Frama_c_kernel__Abstract_interp

(** @canonical Frama_c_kernel.Acsl_extension *)
module Acsl_extension = Frama_c_kernel__Acsl_extension

(** @canonical Frama_c_kernel.Alarms *)
module Alarms = Frama_c_kernel__Alarms

(** @canonical Frama_c_kernel.Allocates *)
module Allocates = Frama_c_kernel__Allocates

(** @canonical Frama_c_kernel.Alpha *)
module Alpha = Frama_c_kernel__Alpha

(** @canonical Frama_c_kernel.Annotations *)
module Annotations = Frama_c_kernel__Annotations

(** @canonical Frama_c_kernel.Asm_contracts *)
module Asm_contracts = Frama_c_kernel__Asm_contracts

(** @canonical Frama_c_kernel.Ast *)
module Ast = Frama_c_kernel__Ast

(** @canonical Frama_c_kernel.Ast_diff *)
module Ast_diff = Frama_c_kernel__Ast_diff

(** @canonical Frama_c_kernel.Ast_info *)
module Ast_info = Frama_c_kernel__Ast_info

(** @canonical Frama_c_kernel.Async *)
module Async = Frama_c_kernel__Async

(** @canonical Frama_c_kernel.Bag *)
module Bag = Frama_c_kernel__Bag

(** @canonical Frama_c_kernel.Base *)
module Base = Frama_c_kernel__Base

(** @canonical Frama_c_kernel.Binary_cache *)
module Binary_cache = Frama_c_kernel__Binary_cache

(** @canonical Frama_c_kernel.Bit_utils *)
module Bit_utils = Frama_c_kernel__Bit_utils

(** @canonical Frama_c_kernel.Bitvector *)
module Bitvector = Frama_c_kernel__Bitvector

(** @canonical Frama_c_kernel.Boot *)
module Boot = Frama_c_kernel__Boot

(** @canonical Frama_c_kernel.Cabs *)
module Cabs = Frama_c_kernel__Cabs

(** @canonical Frama_c_kernel.Cabs2cil *)
module Cabs2cil = Frama_c_kernel__Cabs2cil

(** @canonical Frama_c_kernel.Cabs_debug *)
module Cabs_debug = Frama_c_kernel__Cabs_debug

(** @canonical Frama_c_kernel.Cabshelper *)
module Cabshelper = Frama_c_kernel__Cabshelper

(** @canonical Frama_c_kernel.Cabsvisit *)
module Cabsvisit = Frama_c_kernel__Cabsvisit

(** @canonical Frama_c_kernel.Cfg *)
module Cfg = Frama_c_kernel__Cfg

(** @canonical Frama_c_kernel.Cil *)
module Cil = Frama_c_kernel__Cil

(** @canonical Frama_c_kernel.Cil_builder *)
module Cil_builder = Frama_c_kernel__Cil_builder

(** @canonical Frama_c_kernel.Cil_builtins *)
module Cil_builtins = Frama_c_kernel__Cil_builtins

(** @canonical Frama_c_kernel.Cil_const *)
module Cil_const = Frama_c_kernel__Cil_const

(** @canonical Frama_c_kernel.Cil_datatype *)
module Cil_datatype = Frama_c_kernel__Cil_datatype

(** @canonical Frama_c_kernel.Cil_descriptive_printer *)
module Cil_descriptive_printer = Frama_c_kernel__Cil_descriptive_printer

(** @canonical Frama_c_kernel.Cil_printer *)
module Cil_printer = Frama_c_kernel__Cil_printer

(** @canonical Frama_c_kernel.Cil_state_builder *)
module Cil_state_builder = Frama_c_kernel__Cil_state_builder

(** @canonical Frama_c_kernel.Cil_types *)
module Cil_types = Frama_c_kernel__Cil_types

(** @canonical Frama_c_kernel.Cil_types_debug *)
module Cil_types_debug = Frama_c_kernel__Cil_types_debug

(** @canonical Frama_c_kernel.Cilconfig *)
module Cilconfig = Frama_c_kernel__Cilconfig

(** @canonical Frama_c_kernel.Clexer *)
module Clexer = Frama_c_kernel__Clexer

(** @canonical Frama_c_kernel.Clone *)
module Clone = Frama_c_kernel__Clone

(** @canonical Frama_c_kernel.Cmdline *)
module Cmdline = Frama_c_kernel__Cmdline

(** @canonical Frama_c_kernel.Command *)
module Command = Frama_c_kernel__Command

(** @canonical Frama_c_kernel.Config_data *)
module Config_data = Frama_c_kernel__Config_data

(** @canonical Frama_c_kernel.Contract_special_float *)
module Contract_special_float = Frama_c_kernel__Contract_special_float

(** @canonical Frama_c_kernel.Cparser *)
module Cparser = Frama_c_kernel__Cparser

(** @canonical Frama_c_kernel.Cprint *)
module Cprint = Frama_c_kernel__Cprint

(** @canonical Frama_c_kernel.Current_loc *)
module Current_loc = Frama_c_kernel__Current_loc

(** @canonical Frama_c_kernel.Cvalue *)
module Cvalue = Frama_c_kernel__Cvalue

(** @canonical Frama_c_kernel.Dataflow2 *)
module Dataflow2 = Frama_c_kernel__Dataflow2

(** @canonical Frama_c_kernel.Dataflows *)
module Dataflows = Frama_c_kernel__Dataflows

(** @canonical Frama_c_kernel.Datatype *)
module Datatype = Frama_c_kernel__Datatype

(** @canonical Frama_c_kernel.Db *)
module Db = Frama_c_kernel__Db

(** @canonical Frama_c_kernel.Descr *)
module Descr = Frama_c_kernel__Descr

(** @canonical Frama_c_kernel.Description *)
module Description = Frama_c_kernel__Description

(** @canonical Frama_c_kernel.Destructors *)
module Destructors = Frama_c_kernel__Destructors

(** @canonical Frama_c_kernel.Dominators *)
module Dominators = Frama_c_kernel__Dominators

(** @canonical Frama_c_kernel.Dotgraph *)
module Dotgraph = Frama_c_kernel__Dotgraph

(** @canonical Frama_c_kernel.Dump_config *)
module Dump_config = Frama_c_kernel__Dump_config

(** @canonical Frama_c_kernel.Dynamic *)
module Dynamic = Frama_c_kernel__Dynamic

(** @canonical Frama_c_kernel.Dyncall *)
module Dyncall = Frama_c_kernel__Dyncall

(** @canonical Frama_c_kernel.Emitter *)
module Emitter = Frama_c_kernel__Emitter

(** @canonical Frama_c_kernel.Errorloc *)
module Errorloc = Frama_c_kernel__Errorloc

(** @canonical Frama_c_kernel.Escape *)
module Escape = Frama_c_kernel__Escape

(** @canonical Frama_c_kernel.Eva_lattice_type *)
module Eva_lattice_type = Frama_c_kernel__Eva_lattice_type

(** @canonical Frama_c_kernel.Exn_flow *)
module Exn_flow = Frama_c_kernel__Exn_flow

(** @canonical Frama_c_kernel.Extlib *)
module Extlib = Frama_c_kernel__Extlib

(** @canonical Frama_c_kernel.FCHashtbl *)
module FCHashtbl = Frama_c_kernel__FCHashtbl

(** @canonical Frama_c_kernel.Fc_float *)
module Fc_float = Frama_c_kernel__Fc_float

(** @canonical Frama_c_kernel.Field *)
module Field = Frama_c_kernel__Field

(** @canonical Frama_c_kernel.File *)
module File = Frama_c_kernel__File

(** @canonical Frama_c_kernel.Filecheck *)
module Filecheck = Frama_c_kernel__Filecheck

(** @canonical Frama_c_kernel.Filepath *)
module Filepath = Frama_c_kernel__Filepath

(** @canonical Frama_c_kernel.Filter *)
module Filter = Frama_c_kernel__Filter

(** @canonical Frama_c_kernel.Finite *)
module Finite = Frama_c_kernel__Finite

(** @canonical Frama_c_kernel.Float_interval *)
module Float_interval = Frama_c_kernel__Float_interval

(** @canonical Frama_c_kernel.Float_interval_sig *)
module Float_interval_sig = Frama_c_kernel__Float_interval_sig

(** @canonical Frama_c_kernel.Float_sig *)
module Float_sig = Frama_c_kernel__Float_sig

(** @canonical Frama_c_kernel.Floating_point *)
module Floating_point = Frama_c_kernel__Floating_point

(** @canonical Frama_c_kernel.Frontc *)
module Frontc = Frama_c_kernel__Frontc

(** @canonical Frama_c_kernel.Fval *)
module Fval = Frama_c_kernel__Fval

(** @canonical Frama_c_kernel.Ghost_accesses *)
module Ghost_accesses = Frama_c_kernel__Ghost_accesses

(** @canonical Frama_c_kernel.Ghost_cfg *)
module Ghost_cfg = Frama_c_kernel__Ghost_cfg

(** @canonical Frama_c_kernel.Globals *)
module Globals = Frama_c_kernel__Globals

(** @canonical Frama_c_kernel.Hook *)
module Hook = Frama_c_kernel__Hook

(** @canonical Frama_c_kernel.Hptmap *)
module Hptmap = Frama_c_kernel__Hptmap

(** @canonical Frama_c_kernel.Hptmap_sig *)
module Hptmap_sig = Frama_c_kernel__Hptmap_sig

(** @canonical Frama_c_kernel.Hptset *)
module Hptset = Frama_c_kernel__Hptset

(** @canonical Frama_c_kernel.Indexer *)
module Indexer = Frama_c_kernel__Indexer

(** @canonical Frama_c_kernel.Infer_assigns *)
module Infer_assigns = Frama_c_kernel__Infer_assigns

(** @canonical Frama_c_kernel.Inline *)
module Inline = Frama_c_kernel__Inline

(** @canonical Frama_c_kernel.Inline_stmt_contracts *)
module Inline_stmt_contracts = Frama_c_kernel__Inline_stmt_contracts

(** @canonical Frama_c_kernel.Inout_type *)
module Inout_type = Frama_c_kernel__Inout_type

(** @canonical Frama_c_kernel.Int_Base *)
module Int_Base = Frama_c_kernel__Int_Base

(** @canonical Frama_c_kernel.Int_Intervals *)
module Int_Intervals = Frama_c_kernel__Int_Intervals

(** @canonical Frama_c_kernel.Int_Intervals_sig *)
module Int_Intervals_sig = Frama_c_kernel__Int_Intervals_sig

(** @canonical Frama_c_kernel.Int_interval *)
module Int_interval = Frama_c_kernel__Int_interval

(** @canonical Frama_c_kernel.Int_set *)
module Int_set = Frama_c_kernel__Int_set

(** @canonical Frama_c_kernel.Int_val *)
module Int_val = Frama_c_kernel__Int_val

(** @canonical Frama_c_kernel.Integer *)
module Integer = Frama_c_kernel__Integer

(** @canonical Frama_c_kernel.Interpreted_automata *)
module Interpreted_automata = Frama_c_kernel__Interpreted_automata

(** @canonical Frama_c_kernel.Ival *)
module Ival = Frama_c_kernel__Ival

(** @canonical Frama_c_kernel.Json *)
module Json = Frama_c_kernel__Json

(** @canonical Frama_c_kernel.Json_compilation_database *)
module Json_compilation_database = Frama_c_kernel__Json_compilation_database

(** @canonical Frama_c_kernel.Kernel *)
module Kernel = Frama_c_kernel__Kernel

(** @canonical Frama_c_kernel.Kernel_function *)
module Kernel_function = Frama_c_kernel__Kernel_function

(** @canonical Frama_c_kernel.Lattice_bounds *)
module Lattice_bounds = Frama_c_kernel__Lattice_bounds

(** @canonical Frama_c_kernel.Lattice_type *)
module Lattice_type = Frama_c_kernel__Lattice_type

(** @canonical Frama_c_kernel.Lexerhack *)
module Lexerhack = Frama_c_kernel__Lexerhack

(** @canonical Frama_c_kernel.Linear *)
module Linear = Frama_c_kernel__Linear

(** @canonical Frama_c_kernel.Linear_filter *)
module Linear_filter = Frama_c_kernel__Linear_filter

(** @canonical Frama_c_kernel.Linear_filter_test *)
module Linear_filter_test = Frama_c_kernel__Linear_filter_test

(** @canonical Frama_c_kernel.Lmap *)
module Lmap = Frama_c_kernel__Lmap

(** @canonical Frama_c_kernel.Lmap_bitwise *)
module Lmap_bitwise = Frama_c_kernel__Lmap_bitwise

(** @canonical Frama_c_kernel.Lmap_sig *)
module Lmap_sig = Frama_c_kernel__Lmap_sig

(** @canonical Frama_c_kernel.Locations *)
module Locations = Frama_c_kernel__Locations

(** @canonical Frama_c_kernel.Log *)
module Log = Frama_c_kernel__Log

(** @canonical Frama_c_kernel.Logic_builtin *)
module Logic_builtin = Frama_c_kernel__Logic_builtin

(** @canonical Frama_c_kernel.Logic_const *)
module Logic_const = Frama_c_kernel__Logic_const

(** @canonical Frama_c_kernel.Logic_deps *)
module Logic_deps = Frama_c_kernel__Logic_deps

(** @canonical Frama_c_kernel.Logic_env *)
module Logic_env = Frama_c_kernel__Logic_env

(** @canonical Frama_c_kernel.Logic_lexer *)
module Logic_lexer = Frama_c_kernel__Logic_lexer

(** @canonical Frama_c_kernel.Logic_parse_string *)
module Logic_parse_string = Frama_c_kernel__Logic_parse_string

(** @canonical Frama_c_kernel.Logic_parser *)
module Logic_parser = Frama_c_kernel__Logic_parser

(** @canonical Frama_c_kernel.Logic_preprocess *)
module Logic_preprocess = Frama_c_kernel__Logic_preprocess

(** @canonical Frama_c_kernel.Logic_print *)
module Logic_print = Frama_c_kernel__Logic_print

(** @canonical Frama_c_kernel.Logic_ptree *)
module Logic_ptree = Frama_c_kernel__Logic_ptree

(** @canonical Frama_c_kernel.Logic_to_c *)
module Logic_to_c = Frama_c_kernel__Logic_to_c

(** @canonical Frama_c_kernel.Logic_typing *)
module Logic_typing = Frama_c_kernel__Logic_typing

(** @canonical Frama_c_kernel.Logic_utils *)
module Logic_utils = Frama_c_kernel__Logic_utils

(** @canonical Frama_c_kernel.Loop *)
module Loop = Frama_c_kernel__Loop

(** @canonical Frama_c_kernel.Machdep *)
module Machdep = Frama_c_kernel__Machdep

(** @canonical Frama_c_kernel.Machine *)
module Machine = Frama_c_kernel__Machine

(** @canonical Frama_c_kernel.Macos_dirs *)
module Macos_dirs = Frama_c_kernel__Macos_dirs

(** @canonical Frama_c_kernel.Map_lattice *)
module Map_lattice = Frama_c_kernel__Map_lattice

(** @canonical Frama_c_kernel.Markdown *)
module Markdown = Frama_c_kernel__Markdown

(** @canonical Frama_c_kernel.Mergecil *)
module Mergecil = Frama_c_kernel__Mergecil

(** @canonical Frama_c_kernel.Messages *)
module Messages = Frama_c_kernel__Messages

(** @canonical Frama_c_kernel.Nat *)
module Nat = Frama_c_kernel__Nat

(** @canonical Frama_c_kernel.Offsetmap *)
module Offsetmap = Frama_c_kernel__Offsetmap

(** @canonical Frama_c_kernel.Offsetmap_bitwise_sig *)
module Offsetmap_bitwise_sig = Frama_c_kernel__Offsetmap_bitwise_sig

(** @canonical Frama_c_kernel.Offsetmap_lattice_with_isotropy *)
module Offsetmap_lattice_with_isotropy = Frama_c_kernel__Offsetmap_lattice_with_isotropy

(** @canonical Frama_c_kernel.Offsetmap_sig *)
module Offsetmap_sig = Frama_c_kernel__Offsetmap_sig

(** @canonical Frama_c_kernel.Oneret *)
module Oneret = Frama_c_kernel__Oneret

(** @canonical Frama_c_kernel.Option *)
module Option = Frama_c_kernel__Option

(** @canonical Frama_c_kernel.Ordered_stmt *)
module Ordered_stmt = Frama_c_kernel__Ordered_stmt

(** @canonical Frama_c_kernel.Origin *)
module Origin = Frama_c_kernel__Origin

(** @canonical Frama_c_kernel.Parameter_builder *)
module Parameter_builder = Frama_c_kernel__Parameter_builder

(** @canonical Frama_c_kernel.Parameter_category *)
module Parameter_category = Frama_c_kernel__Parameter_category

(** @canonical Frama_c_kernel.Parameter_customize *)
module Parameter_customize = Frama_c_kernel__Parameter_customize

(** @canonical Frama_c_kernel.Parameter_sig *)
module Parameter_sig = Frama_c_kernel__Parameter_sig

(** @canonical Frama_c_kernel.Parameter_state *)
module Parameter_state = Frama_c_kernel__Parameter_state

(** @canonical Frama_c_kernel.Parray *)
module Parray = Frama_c_kernel__Parray

(** @canonical Frama_c_kernel.Parse_env *)
module Parse_env = Frama_c_kernel__Parse_env

(** @canonical Frama_c_kernel.Plugin *)
module Plugin = Frama_c_kernel__Plugin

(** @canonical Frama_c_kernel.Populate_spec *)
module Populate_spec = Frama_c_kernel__Populate_spec

(** @canonical Frama_c_kernel.Precise_locs *)
module Precise_locs = Frama_c_kernel__Precise_locs

(** @canonical Frama_c_kernel.Pretty_utils *)
module Pretty_utils = Frama_c_kernel__Pretty_utils

(** @canonical Frama_c_kernel.Printer *)
module Printer = Frama_c_kernel__Printer

(** @canonical Frama_c_kernel.Printer_api *)
module Printer_api = Frama_c_kernel__Printer_api

(** @canonical Frama_c_kernel.Printer_builder *)
module Printer_builder = Frama_c_kernel__Printer_builder

(** @canonical Frama_c_kernel.Printer_tag *)
module Printer_tag = Frama_c_kernel__Printer_tag

(** @canonical Frama_c_kernel.Project *)
module Project = Frama_c_kernel__Project

(** @canonical Frama_c_kernel.Project_skeleton *)
module Project_skeleton = Frama_c_kernel__Project_skeleton

(** @canonical Frama_c_kernel.Property *)
module Property = Frama_c_kernel__Property

(** @canonical Frama_c_kernel.Property_status *)
module Property_status = Frama_c_kernel__Property_status

(** @canonical Frama_c_kernel.Qstack *)
module Qstack = Frama_c_kernel__Qstack

(** @canonical Frama_c_kernel.Rangemap *)
module Rangemap = Frama_c_kernel__Rangemap

(** @canonical Frama_c_kernel.Result *)
module Result = Frama_c_kernel__Result

(** @canonical Frama_c_kernel.Rgmap *)
module Rgmap = Frama_c_kernel__Rgmap

(** @canonical Frama_c_kernel.Rich_text *)
module Rich_text = Frama_c_kernel__Rich_text

(** @canonical Frama_c_kernel.Rmtmps *)
module Rmtmps = Frama_c_kernel__Rmtmps

(** @canonical Frama_c_kernel.Sanitizer *)
module Sanitizer = Frama_c_kernel__Sanitizer

(** @canonical Frama_c_kernel.Service_graph *)
module Service_graph = Frama_c_kernel__Service_graph

(** @canonical Frama_c_kernel.Special_hooks *)
module Special_hooks = Frama_c_kernel__Special_hooks

(** @canonical Frama_c_kernel.State *)
module State = Frama_c_kernel__State

(** @canonical Frama_c_kernel.State_builder *)
module State_builder = Frama_c_kernel__State_builder

(** @canonical Frama_c_kernel.State_dependency_graph *)
module State_dependency_graph = Frama_c_kernel__State_dependency_graph

(** @canonical Frama_c_kernel.State_selection *)
module State_selection = Frama_c_kernel__State_selection

(** @canonical Frama_c_kernel.State_topological *)
module State_topological = Frama_c_kernel__State_topological

(** @canonical Frama_c_kernel.Statuses_by_call *)
module Statuses_by_call = Frama_c_kernel__Statuses_by_call

(** @canonical Frama_c_kernel.Stmts_graph *)
module Stmts_graph = Frama_c_kernel__Stmts_graph

(** @canonical Frama_c_kernel.Structural_descr *)
module Structural_descr = Frama_c_kernel__Structural_descr

(** @canonical Frama_c_kernel.Substitute_const_globals *)
module Substitute_const_globals = Frama_c_kernel__Substitute_const_globals

(** @canonical Frama_c_kernel.System_config *)
module System_config = Frama_c_kernel__System_config

(** @canonical Frama_c_kernel.Task *)
module Task = Frama_c_kernel__Task

(** @canonical Frama_c_kernel.Tr_offset *)
module Tr_offset = Frama_c_kernel__Tr_offset

(** @canonical Frama_c_kernel.Translate_lightweight *)
module Translate_lightweight = Frama_c_kernel__Translate_lightweight

(** @canonical Frama_c_kernel.Type *)
module Type = Frama_c_kernel__Type

(** @canonical Frama_c_kernel.Typed_parameter *)
module Typed_parameter = Frama_c_kernel__Typed_parameter

(** @canonical Frama_c_kernel.Undefined_sequence *)
module Undefined_sequence = Frama_c_kernel__Undefined_sequence

(** @canonical Frama_c_kernel.Unfold_loops *)
module Unfold_loops = Frama_c_kernel__Unfold_loops

(** @canonical Frama_c_kernel.Unicode *)
module Unicode = Frama_c_kernel__Unicode

(** @canonical Frama_c_kernel.Unix_dirs *)
module Unix_dirs = Frama_c_kernel__Unix_dirs

(** @canonical Frama_c_kernel.Unmarshal *)
module Unmarshal = Frama_c_kernel__Unmarshal

(** @canonical Frama_c_kernel.Unmarshal_z *)
module Unmarshal_z = Frama_c_kernel__Unmarshal_z

(** @canonical Frama_c_kernel.Utf8_logic *)
module Utf8_logic = Frama_c_kernel__Utf8_logic

(** @canonical Frama_c_kernel.Vector *)
module Vector = Frama_c_kernel__Vector

(** @canonical Frama_c_kernel.Visitor *)
module Visitor = Frama_c_kernel__Visitor

(** @canonical Frama_c_kernel.Visitor_behavior *)
module Visitor_behavior = Frama_c_kernel__Visitor_behavior

(** @canonical Frama_c_kernel.Widen_type *)
module Widen_type = Frama_c_kernel__Widen_type

(** @canonical Frama_c_kernel.Win_dirs *)
module Win_dirs = Frama_c_kernel__Win_dirs

(** @canonical Frama_c_kernel.Wto *)
module Wto = Frama_c_kernel__Wto

(** @canonical Frama_c_kernel.Wto_statement *)
module Wto_statement = Frama_c_kernel__Wto_statement
