name: docs
on:
  push:

permissions:
  contents: write
jobs:
  build:
    concurrency: ci-${{ github.ref }} # Recommended if you intend to make multiple deployments in quick succession.
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # fetch all history such that subst gives nice version

      - name: Setup OCaml ${{ matrix.ocaml-version }}
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: 4.13.1

      - run: opam pin add goblint-cil.dev . --no-action
      - run: opam depext goblint-cil --yes
      - run: opam depext goblint-cil --yes --with-doc
      - run: opam install . --deps-only --with-doc
      - name: Install and Build 🔧 # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
        run: |
          opam exec -- dune subst
          opam exec -- dune build @heveadoc

      - uses: actions/upload-artifact@v4
        with:
          name: doc-html
          path: _build/default/doc/html/cil

  deploy:
    if: github.ref == 'refs/heads/develop'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3 # check out git repo to make deploy action happy

      - uses: actions/download-artifact@v4
        with:
          name: doc-html
          path: _build/default/doc/html/cil

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: _build/default/doc/html/cil
