(* generated by dune *)

(** @canonical LoopAnalysis.Loop_analysis *)
module Loop_analysis = LoopAnalysis__Loop_analysis

(** @canonical LoopAnalysis.Options *)
module Options = LoopAnalysis__Options

(** @canonical LoopAnalysis.Region_analysis *)
module Region_analysis = LoopAnalysis__Region_analysis

(** @canonical LoopAnalysis.Region_analysis_sig *)
module Region_analysis_sig = LoopAnalysis__Region_analysis_sig

(** @canonical LoopAnalysis.Region_analysis_stmt *)
module Region_analysis_stmt = LoopAnalysis__Region_analysis_stmt

(** @canonical LoopAnalysis.Register *)
module Register = LoopAnalysis__Register

module LoopAnalysis__ = struct end
[@@deprecated "this module is shadowed"]
