(* generated by dune *)

(** @canonical Inout.Context *)
module Context = Inout__Context

(** @canonical Inout.Cumulative_analysis *)
module Cumulative_analysis = Inout__Cumulative_analysis

(** @canonical Inout.Derefs *)
module Derefs = Inout__Derefs

(** @canonical Inout.Inout_parameters *)
module Inout_parameters = Inout__Inout_parameters

(** @canonical Inout.Inputs *)
module Inputs = Inout__Inputs

(** @canonical Inout.Operational_inputs *)
module Operational_inputs = Inout__Operational_inputs

(** @canonical Inout.Outputs *)
module Outputs = Inout__Outputs

(** @canonical Inout.Register *)
module Register = Inout__Register

module Inout__ = struct end
[@@deprecated "this module is shadowed"]
