(* generated by dune *)

(** @canonical Region.Access *)
module Access = Region__Access

(** @canonical Region.Analysis *)
module Analysis = Region__Analysis

(** @canonical Region.Annot *)
module Annot = Region__Annot

(** @canonical Region.Code *)
module Code = Region__Code

(** @canonical Region.Fields *)
module Fields = Region__Fields

(** @canonical Region.Logic *)
module Logic = Region__Logic

(** @canonical Region.Memory *)
module Memory = Region__Memory

(** @canonical Region.Options *)
module Options = Region__Options

(** @canonical Region.Ranges *)
module Ranges = Region__Ranges

(** @canonical Region.Register *)
module Register = Region__Register

(** @canonical Region.Services *)
module Services = Region__Services

(** @canonical Region.Store *)
module Store = Region__Store

module Region__ = struct end
[@@deprecated "this module is shadowed"]
