(* generated by dune *)

(** @canonical Reduc.Collect *)
module Collect = Reduc__Collect

(** @canonical Reduc.Hyp *)
module Hyp = Reduc__Hyp

(** @canonical Reduc.Misc *)
module Misc = Reduc__Misc

(** @canonical Reduc.Reduc_options *)
module Reduc_options = Reduc__Reduc_options

(** @canonical Reduc.Register *)
module Register = Reduc__Register

(** @canonical Reduc.Value2acsl *)
module Value2acsl = Reduc__Value2acsl

module Reduc__ = struct end
[@@deprecated "this module is shadowed"]
