(* generated by dune *)

(** @canonical FmSimplexPlugin.FmSimplexIneqs *)
module FmSimplexIneqs = FmSimplexPlugin__FmSimplexIneqs

(** @canonical FmSimplexPlugin.Simplex *)
module Simplex = FmSimplexPlugin__Simplex

(** @canonical FmSimplexPlugin.Simplex_cache *)
module Simplex_cache = FmSimplexPlugin__Simplex_cache
