name: Build

on:
  push:
  pull_request:

permissions: {}

env:
  OCAML_DEFAULT_VERSION: 4.08.1
  # Add OPAMYES=true to the environment, this is usefill to replace `-y` option
  # in any opam call
  OPAMYES: true

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
        ocaml-compiler:
          - 4.08.1
          - 5.0.0

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Use OCaml ${{ matrix.ocaml-compiler }}
        uses: ocaml/setup-ocaml@v2
        with:
          allow-prerelease-opam: true
          ocaml-compiler: ${{ matrix.ocaml-compiler }}
          dune-cache: true

      - name: Install dependencies
        run: opam exec -- opam install -y . --locked --deps-only --with-test

      - name: Build ocplib-simplex with opam
        run: opam exec -- opam reinstall .

      - name: Run tests
        run: opam exec -- make test
