name: Documentation

on:
  push:
    branches:
      - master

env:
  OCAML_DEFAULT_VERSION: 5.0.0
  OPAMYES: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      OPAMWITHDOC: true

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use OCaml ${{ env.OCAML_DEFAULT_VERSION }}
        uses: ocaml/setup-ocaml@v2
        with:
          allow-prerelease-opam: true
          ocaml-compiler: ${{ env.OCAML_DEFAULT_VERSION }}
          dune-cache: true

      - name: Install dependencies
        run: opam install . --deps-only --with-doc

      - name: Make odoc documentation
        run: opam exec -- make doc

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: _build/default/_doc/_html/
