(* generated by dune *)

(** @canonical Security_slicing.Components *)
module Components = Security_slicing__Components

(** @canonical Security_slicing.Security_slicing_parameters *)
module Security_slicing_parameters = Security_slicing__Security_slicing_parameters

module Security_slicing__ = struct end
[@@deprecated "this module is shadowed"]
