(* generated by dune *)

(** @canonical Frama_c_very_first.Frama_c_init *)
module Frama_c_init = Frama_c_very_first__Frama_c_init

(** @canonical Frama_c_very_first.Gui_init *)
module Gui_init = Frama_c_very_first__Gui_init
