(* generated by dune *)

(** @canonical Frama_c_gui.Analyses_manager *)
module Analyses_manager = Frama_c_gui__Analyses_manager

(** @canonical Frama_c_gui.Book_manager *)
module Book_manager = Frama_c_gui__Book_manager

(** @canonical Frama_c_gui.Design *)
module Design = Frama_c_gui__Design

(** @canonical Frama_c_gui.File_manager *)
module File_manager = Frama_c_gui__File_manager

(** @canonical Frama_c_gui.Filetree *)
module Filetree = Frama_c_gui__Filetree

(** @canonical Frama_c_gui.GSourceView *)
module GSourceView = Frama_c_gui__GSourceView

(** @canonical Frama_c_gui.Gtk_form *)
module Gtk_form = Frama_c_gui__Gtk_form

(** @canonical Frama_c_gui.Gtk_helper *)
module Gtk_helper = Frama_c_gui__Gtk_helper

(** @canonical Frama_c_gui.Gui_parameters *)
module Gui_parameters = Frama_c_gui__Gui_parameters

(** @canonical Frama_c_gui.Gui_printers *)
module Gui_printers = Frama_c_gui__Gui_printers

(** @canonical Frama_c_gui.Help_manager *)
module Help_manager = Frama_c_gui__Help_manager

(** @canonical Frama_c_gui.History *)
module History = Frama_c_gui__History

(** @canonical Frama_c_gui.Launcher *)
module Launcher = Frama_c_gui__Launcher

(** @canonical Frama_c_gui.Menu_manager *)
module Menu_manager = Frama_c_gui__Menu_manager

(** @canonical Frama_c_gui.Pretty_source *)
module Pretty_source = Frama_c_gui__Pretty_source

(** @canonical Frama_c_gui.Project_manager *)
module Project_manager = Frama_c_gui__Project_manager

(** @canonical Frama_c_gui.Property_navigator *)
module Property_navigator = Frama_c_gui__Property_navigator

(** @canonical Frama_c_gui.Source_manager *)
module Source_manager = Frama_c_gui__Source_manager

(** @canonical Frama_c_gui.Source_viewer *)
module Source_viewer = Frama_c_gui__Source_viewer

(** @canonical Frama_c_gui.Warning_manager *)
module Warning_manager = Frama_c_gui__Warning_manager

(** @canonical Frama_c_gui.Wbox *)
module Wbox = Frama_c_gui__Wbox

(** @canonical Frama_c_gui.Wfile *)
module Wfile = Frama_c_gui__Wfile

(** @canonical Frama_c_gui.Widget *)
module Widget = Frama_c_gui__Widget

(** @canonical Frama_c_gui.Wpalette *)
module Wpalette = Frama_c_gui__Wpalette

(** @canonical Frama_c_gui.Wpane *)
module Wpane = Frama_c_gui__Wpane

(** @canonical Frama_c_gui.Wtable *)
module Wtable = Frama_c_gui__Wtable

(** @canonical Frama_c_gui.Wtext *)
module Wtext = Frama_c_gui__Wtext

(** @canonical Frama_c_gui.Wutil *)
module Wutil = Frama_c_gui__Wutil

(** @canonical Frama_c_gui.Wutil_once *)
module Wutil_once = Frama_c_gui__Wutil_once
