(* generated by dune *)

(** @canonical Alias.API *)
module API = Alias__API

(** @canonical Alias.Abstract_state *)
module Abstract_state = Alias__Abstract_state

(** @canonical Alias.Analysis *)
module Analysis = Alias__Analysis

(** @canonical Alias.Options *)
module Options = Alias__Options

(** @canonical Alias.Simplified *)
module Simplified = Alias__Simplified

module Alias__ = struct end
[@@deprecated "this module is shadowed"]
