(* generated by dune *)

(** @canonical UnionFind.Store *)
module Store = UnionFind__Store

(** @canonical UnionFind.StoreMap *)
module StoreMap = UnionFind__StoreMap

(** @canonical UnionFind.StoreRef *)
module StoreRef = UnionFind__StoreRef

(** @canonical UnionFind.StoreTransactionalRef *)
module StoreTransactionalRef = UnionFind__StoreTransactionalRef

(** @canonical UnionFind.StoreVector *)
module StoreVector = UnionFind__StoreVector

(** @canonical UnionFind.UnionFindBasic *)
module UnionFindBasic = UnionFind__UnionFindBasic

(** @canonical UnionFind.UnionFindOverStore *)
module UnionFindOverStore = UnionFind__UnionFindOverStore
