(* generated by dune *)

(** @canonical Studia.Options *)
module Options = Studia__Options

(** @canonical Studia.Reads *)
module Reads = Studia__Reads

(** @canonical Studia.Studia_request *)
module Studia_request = Studia__Studia_request

(** @canonical Studia.Writes *)
module Writes = Studia__Writes

module Studia__ = struct end
[@@deprecated "this module is shadowed"]
