(* generated by dune *)

(** @canonical Report.Classify *)
module Classify = Report__Classify

(** @canonical Report.Csv *)
module Csv = Report__Csv

(** @canonical Report.Dump *)
module Dump = Report__Dump

(** @canonical Report.Register *)
module Register = Report__Register

(** @canonical Report.Report_parameters *)
module Report_parameters = Report__Report_parameters

(** @canonical Report.Scan *)
module Scan = Report__Scan

module Report__ = struct end
[@@deprecated "this module is shadowed"]
