(* generated by dune *)

(** @canonical Eva.Abstract *)
module Abstract = Eva__Abstract

(** @canonical Eva.Abstract_context *)
module Abstract_context = Eva__Abstract_context

(** @canonical Eva.Abstract_domain *)
module Abstract_domain = Eva__Abstract_domain

(** @canonical Eva.Abstract_location *)
module Abstract_location = Eva__Abstract_location

(** @canonical Eva.Abstract_memory *)
module Abstract_memory = Eva__Abstract_memory

(** @canonical Eva.Abstract_offset *)
module Abstract_offset = Eva__Abstract_offset

(** @canonical Eva.Abstract_structure *)
module Abstract_structure = Eva__Abstract_structure

(** @canonical Eva.Abstract_value *)
module Abstract_value = Eva__Abstract_value

(** @canonical Eva.Abstractions *)
module Abstractions = Eva__Abstractions

(** @canonical Eva.Active_behaviors *)
module Active_behaviors = Eva__Active_behaviors

(** @canonical Eva.Alarmset *)
module Alarmset = Eva__Alarmset

(** @canonical Eva.Analysis *)
module Analysis = Eva__Analysis

(** @canonical Eva.Assigns *)
module Assigns = Eva__Assigns

(** @canonical Eva.Auto_loop_unroll *)
module Auto_loop_unroll = Eva__Auto_loop_unroll

(** @canonical Eva.Backward_formals *)
module Backward_formals = Eva__Backward_formals

(** @canonical Eva.Builtins *)
module Builtins = Eva__Builtins

(** @canonical Eva.Builtins_float *)
module Builtins_float = Eva__Builtins_float

(** @canonical Eva.Builtins_malloc *)
module Builtins_malloc = Eva__Builtins_malloc

(** @canonical Eva.Builtins_memory *)
module Builtins_memory = Eva__Builtins_memory

(** @canonical Eva.Builtins_misc *)
module Builtins_misc = Eva__Builtins_misc

(** @canonical Eva.Builtins_print_c *)
module Builtins_print_c = Eva__Builtins_print_c

(** @canonical Eva.Builtins_split *)
module Builtins_split = Eva__Builtins_split

(** @canonical Eva.Builtins_string *)
module Builtins_string = Eva__Builtins_string

(** @canonical Eva.Builtins_watchpoint *)
module Builtins_watchpoint = Eva__Builtins_watchpoint

(** @canonical Eva.Callstack *)
module Callstack = Eva__Callstack

(** @canonical Eva.Compute_functions *)
module Compute_functions = Eva__Compute_functions

(** @canonical Eva.Context_product *)
module Context_product = Eva__Context_product

(** @canonical Eva.Cvalue_backward *)
module Cvalue_backward = Eva__Cvalue_backward

(** @canonical Eva.Cvalue_callbacks *)
module Cvalue_callbacks = Eva__Cvalue_callbacks

(** @canonical Eva.Cvalue_domain *)
module Cvalue_domain = Eva__Cvalue_domain

(** @canonical Eva.Cvalue_forward *)
module Cvalue_forward = Eva__Cvalue_forward

(** @canonical Eva.Cvalue_init *)
module Cvalue_init = Eva__Cvalue_init

(** @canonical Eva.Cvalue_offsetmap *)
module Cvalue_offsetmap = Eva__Cvalue_offsetmap

(** @canonical Eva.Cvalue_queries *)
module Cvalue_queries = Eva__Cvalue_queries

(** @canonical Eva.Cvalue_results *)
module Cvalue_results = Eva__Cvalue_results

(** @canonical Eva.Cvalue_transfer *)
module Cvalue_transfer = Eva__Cvalue_transfer

(** @canonical Eva.Deps *)
module Deps = Eva__Deps

(** @canonical Eva.Domain_builder *)
module Domain_builder = Eva__Domain_builder

(** @canonical Eva.Domain_lift *)
module Domain_lift = Eva__Domain_lift

(** @canonical Eva.Domain_mode *)
module Domain_mode = Eva__Domain_mode

(** @canonical Eva.Domain_product *)
module Domain_product = Eva__Domain_product

(** @canonical Eva.Domain_store *)
module Domain_store = Eva__Domain_store

(** @canonical Eva.Equality *)
module Equality = Eva__Equality

(** @canonical Eva.Equality_domain *)
module Equality_domain = Eva__Equality_domain

(** @canonical Eva.Eva_annotations *)
module Eva_annotations = Eva__Eva_annotations

(** @canonical Eva.Eva_ast *)
module Eva_ast = Eva__Eva_ast

(** @canonical Eva.Eva_ast_builder *)
module Eva_ast_builder = Eva__Eva_ast_builder

(** @canonical Eva.Eva_ast_datatype *)
module Eva_ast_datatype = Eva__Eva_ast_datatype

(** @canonical Eva.Eva_ast_printer *)
module Eva_ast_printer = Eva__Eva_ast_printer

(** @canonical Eva.Eva_ast_types *)
module Eva_ast_types = Eva__Eva_ast_types

(** @canonical Eva.Eva_ast_typing *)
module Eva_ast_typing = Eva__Eva_ast_typing

(** @canonical Eva.Eva_ast_utils *)
module Eva_ast_utils = Eva__Eva_ast_utils

(** @canonical Eva.Eva_ast_visitor *)
module Eva_ast_visitor = Eva__Eva_ast_visitor

(** @canonical Eva.Eva_audit *)
module Eva_audit = Eva__Eva_audit

(** @canonical Eva.Eva_automata *)
module Eva_automata = Eva__Eva_automata

(** @canonical Eva.Eva_dynamic *)
module Eva_dynamic = Eva__Eva_dynamic

(** @canonical Eva.Eva_perf *)
module Eva_perf = Eva__Eva_perf

(** @canonical Eva.Eva_results *)
module Eva_results = Eva__Eva_results

(** @canonical Eva.Eva_utils *)
module Eva_utils = Eva__Eva_utils

(** @canonical Eva.Eval *)
module Eval = Eva__Eval

(** @canonical Eva.Eval_annots *)
module Eval_annots = Eva__Eval_annots

(** @canonical Eva.Eval_op *)
module Eval_op = Eva__Eval_op

(** @canonical Eva.Eval_terms *)
module Eval_terms = Eva__Eval_terms

(** @canonical Eva.Eval_typ *)
module Eval_typ = Eva__Eval_typ

(** @canonical Eva.Evaluation *)
module Evaluation = Eva__Evaluation

(** @canonical Eva.Evaluation_sig *)
module Evaluation_sig = Eva__Evaluation_sig

(** @canonical Eva.Function_calls *)
module Function_calls = Eva__Function_calls

(** @canonical Eva.Gauges_domain *)
module Gauges_domain = Eva__Gauges_domain

(** @canonical Eva.General_requests *)
module General_requests = Eva__General_requests

(** @canonical Eva.Hcexprs *)
module Hcexprs = Eva__Hcexprs

(** @canonical Eva.Initialization *)
module Initialization = Eva__Initialization

(** @canonical Eva.Inout_domain *)
module Inout_domain = Eva__Inout_domain

(** @canonical Eva.Iterator *)
module Iterator = Eva__Iterator

(** @canonical Eva.Library_functions *)
module Library_functions = Eva__Library_functions

(** @canonical Eva.Locals_scoping *)
module Locals_scoping = Eva__Locals_scoping

(** @canonical Eva.Location_lift *)
module Location_lift = Eva__Location_lift

(** @canonical Eva.Locations_product *)
module Locations_product = Eva__Locations_product

(** @canonical Eva.Logic_inout *)
module Logic_inout = Eva__Logic_inout

(** @canonical Eva.Main_locations *)
module Main_locations = Eva__Main_locations

(** @canonical Eva.Main_values *)
module Main_values = Eva__Main_values

(** @canonical Eva.Mem_exec *)
module Mem_exec = Eva__Mem_exec

(** @canonical Eva.Multidim *)
module Multidim = Eva__Multidim

(** @canonical Eva.Multidim_domain *)
module Multidim_domain = Eva__Multidim_domain

(** @canonical Eva.Octagons *)
module Octagons = Eva__Octagons

(** @canonical Eva.Offsm_domain *)
module Offsm_domain = Eva__Offsm_domain

(** @canonical Eva.Offsm_value *)
module Offsm_value = Eva__Offsm_value

(** @canonical Eva.Parameters *)
module Parameters = Eva__Parameters

(** @canonical Eva.Partition *)
module Partition = Eva__Partition

(** @canonical Eva.Partitioning_index *)
module Partitioning_index = Eva__Partitioning_index

(** @canonical Eva.Partitioning_parameters *)
module Partitioning_parameters = Eva__Partitioning_parameters

(** @canonical Eva.Per_stmt_slevel *)
module Per_stmt_slevel = Eva__Per_stmt_slevel

(** @canonical Eva.Powerset *)
module Powerset = Eva__Powerset

(** @canonical Eva.Pretty_memory *)
module Pretty_memory = Eva__Pretty_memory

(** @canonical Eva.Printer_domain *)
module Printer_domain = Eva__Printer_domain

(** @canonical Eva.Private *)
module Private = Eva__Private

(** @canonical Eva.Recursion *)
module Recursion = Eva__Recursion

(** @canonical Eva.Red_statuses *)
module Red_statuses = Eva__Red_statuses

(** @canonical Eva.Results *)
module Results = Eva__Results

(** @canonical Eva.Segmentation *)
module Segmentation = Eva__Segmentation

(** @canonical Eva.Self *)
module Self = Eva__Self

(** @canonical Eva.Sign_domain *)
module Sign_domain = Eva__Sign_domain

(** @canonical Eva.Sign_value *)
module Sign_value = Eva__Sign_value

(** @canonical Eva.Simple_memory *)
module Simple_memory = Eva__Simple_memory

(** @canonical Eva.Simpler_domains *)
module Simpler_domains = Eva__Simpler_domains

(** @canonical Eva.Split_return *)
module Split_return = Eva__Split_return

(** @canonical Eva.Split_strategy *)
module Split_strategy = Eva__Split_strategy

(** @canonical Eva.Statistics *)
module Statistics = Eva__Statistics

(** @canonical Eva.Structure *)
module Structure = Eva__Structure

(** @canonical Eva.Subdivided_evaluation *)
module Subdivided_evaluation = Eva__Subdivided_evaluation

(** @canonical Eva.Summary *)
module Summary = Eva__Summary

(** @canonical Eva.Symbolic_locs *)
module Symbolic_locs = Eva__Symbolic_locs

(** @canonical Eva.Taint_domain *)
module Taint_domain = Eva__Taint_domain

(** @canonical Eva.Trace_partitioning *)
module Trace_partitioning = Eva__Trace_partitioning

(** @canonical Eva.Traces_domain *)
module Traces_domain = Eva__Traces_domain

(** @canonical Eva.Transfer_logic *)
module Transfer_logic = Eva__Transfer_logic

(** @canonical Eva.Transfer_specification *)
module Transfer_specification = Eva__Transfer_specification

(** @canonical Eva.Transfer_stmt *)
module Transfer_stmt = Eva__Transfer_stmt

(** @canonical Eva.Typed_memory *)
module Typed_memory = Eva__Typed_memory

(** @canonical Eva.Unit_context *)
module Unit_context = Eva__Unit_context

(** @canonical Eva.Unit_domain *)
module Unit_domain = Eva__Unit_domain

(** @canonical Eva.Unit_tests *)
module Unit_tests = Eva__Unit_tests

(** @canonical Eva.Value_lift *)
module Value_lift = Eva__Value_lift

(** @canonical Eva.Value_product *)
module Value_product = Eva__Value_product

(** @canonical Eva.Values_request *)
module Values_request = Eva__Values_request

(** @canonical Eva.Widen *)
module Widen = Eva__Widen

(** @canonical Eva.Widen_hints_ext *)
module Widen_hints_ext = Eva__Widen_hints_ext

module Eva__ = struct end
[@@deprecated "this module is shadowed"]
