(* generated by dune *)

(** @canonical From.Callwise *)
module Callwise = From__Callwise

(** @canonical From.From_compute *)
module From_compute = From__From_compute

(** @canonical From.From_memory *)
module From_memory = From__From_memory

(** @canonical From.From_parameters *)
module From_parameters = From__From_parameters

(** @canonical From.From_register *)
module From_register = From__From_register

(** @canonical From.Functionwise *)
module Functionwise = From__Functionwise

module From__ = struct end
[@@deprecated "this module is shadowed"]
