(* generated by dune *)

(** @canonical Wp_gui.GuiComposer *)
module GuiComposer = Wp_gui__GuiComposer

(** @canonical Wp_gui.GuiConfig *)
module GuiConfig = Wp_gui__GuiConfig

(** @canonical Wp_gui.GuiGoal *)
module GuiGoal = Wp_gui__GuiGoal

(** @canonical Wp_gui.GuiList *)
module GuiList = Wp_gui__GuiList

(** @canonical Wp_gui.GuiNavigator *)
module GuiNavigator = Wp_gui__GuiNavigator

(** @canonical Wp_gui.GuiPanel *)
module GuiPanel = Wp_gui__GuiPanel

(** @canonical Wp_gui.GuiProof *)
module GuiProof = Wp_gui__GuiProof

(** @canonical Wp_gui.GuiProver *)
module GuiProver = Wp_gui__GuiProver

(** @canonical Wp_gui.GuiSequent *)
module GuiSequent = Wp_gui__GuiSequent

(** @canonical Wp_gui.GuiSource *)
module GuiSource = Wp_gui__GuiSource

(** @canonical Wp_gui.GuiTactic *)
module GuiTactic = Wp_gui__GuiTactic
